import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Navbar from "@/components/layout/Navbar";
import {
  ArrowRight,
  Brain,
  Code2,
  Briefcase,
  Youtube,
  FileText,
  Map,
  Sparkles,
  Zap,
  CheckCircle2,
  Target,
  Rocket,
} from "lucide-react";

const features = [
  {
    icon: Youtube,
    title: "AI Video Analysis",
    description: "Extract knowledge from any YouTube video with AI-powered transcript analysis and summarization.",
    details: [
      "Automatic transcript extraction",
      "Key concepts identification",
      "Summary generation",
      "Flashcard creation",
    ],
  },
  {
    icon: FileText,
    title: "Document Intelligence",
    description: "Upload PDFs, resumes, and documents. Our AI parses and understands complex layouts.",
    details: [
      "PDF & document parsing",
      "Resume analysis",
      "Content extraction",
      "Smart formatting",
    ],
  },
  {
    icon: Map,
    title: "Dynamic Roadmaps",
    description: "Get personalized learning paths generated by AI based on your goals and current skills.",
    details: [
      "Personalized learning paths",
      "Skill gap analysis",
      "Progress tracking",
      "Adaptive recommendations",
    ],
  },
  {
    icon: Code2,
    title: "Code Practice",
    description: "Secure sandbox environment with Monaco Editor. Practice in Python, JavaScript, and more.",
    details: [
      "Real-time code execution",
      "Multiple languages",
      "Test case validation",
      "AI-powered hints",
    ],
  },
  {
    icon: Briefcase,
    title: "Smart Job Matching",
    description: "AI-powered semantic matching connects you with perfect job opportunities.",
    details: [
      "Skill-based matching",
      "Resume optimization",
      "Application tracking",
      "Interview prep",
    ],
  },
  {
    icon: Brain,
    title: "AI Career Assistant",
    description: "Get personalized advice, interview prep, and career guidance powered by advanced AI.",
    details: [
      "24/7 availability",
      "Personalized guidance",
      "Interview simulation",
      "Career planning",
    ],
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

const Features = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-4">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-[128px] animate-pulse-glow" />
        </div>

        <div className="container mx-auto relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <Sparkles className="w-12 h-12 text-primary mx-auto mb-4" />
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              Powerful Features for Your <span className="text-gradient">Success</span>
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Everything you need to accelerate your learning journey and land your dream tech job.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 px-4">
        <div className="container mx-auto">
          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {features.map((feature) => (
              <motion.div key={feature.title} variants={itemVariants}>
                <Card variant="feature" className="h-full">
                  <CardHeader>
                    <div className="w-14 h-14 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-4">
                      <feature.icon className="w-7 h-7 text-primary" />
                    </div>
                    <CardTitle className="text-xl mb-2">{feature.title}</CardTitle>
                    <CardDescription className="text-base mb-4">{feature.description}</CardDescription>
                    <ul className="space-y-2">
                      {feature.details.map((detail) => (
                        <li key={detail} className="flex items-center gap-2 text-sm text-muted-foreground">
                          <CheckCircle2 className="w-4 h-4 text-success flex-shrink-0" />
                          {detail}
                        </li>
                      ))}
                    </ul>
                  </CardHeader>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-4 border-t border-border/50">
        <div className="container mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How It <span className="text-gradient">Works</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Get started in minutes and transform your career path
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              { icon: Target, title: "Set Your Goal", description: "Tell us what career path you want to pursue" },
              { icon: Map, title: "Get Your Roadmap", description: "AI generates a personalized learning path" },
              { icon: Rocket, title: "Start Learning", description: "Practice, learn, and land your dream job" },
            ].map((step, index) => (
              <motion.div
                key={step.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                viewport={{ once: true }}
                className="text-center"
              >
                <div className="w-16 h-16 rounded-2xl bg-gradient-primary flex items-center justify-center mx-auto mb-4 glow">
                  <step.icon className="w-8 h-8 text-primary-foreground" />
                </div>
                <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                <p className="text-muted-foreground">{step.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-4">
        <div className="container mx-auto">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="glass rounded-3xl p-12 text-center max-w-3xl mx-auto"
          >
            <Zap className="w-12 h-12 text-primary mx-auto mb-4" />
            <h2 className="text-3xl font-bold mb-4">Ready to Get Started?</h2>
            <p className="text-lg text-muted-foreground mb-8">
              Join thousands of learners already transforming their careers.
            </p>
            <Button variant="hero" size="xl" asChild>
              <Link to="/auth">
                Start Free Today
                <ArrowRight className="w-5 h-5 ml-2" />
              </Link>
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 border-t border-border/50">
        <div className="container mx-auto text-center text-muted-foreground">
          <p>© 2025 EduForce AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Features;
