import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Navbar from "@/components/layout/Navbar";
import {
  ArrowRight,
  Brain,
  Code2,
  Briefcase,
  Youtube,
  FileText,
  Map,
  CheckCircle2,
  Target,
  Rocket,
  Zap,
  Sparkles,
} from "lucide-react";

const features = [
  {
    icon: Youtube,
    title: "AI Video Analysis",
    description: "Extract knowledge from any YouTube video with AI-powered transcript analysis and summarization.",
    details: [
      "Automatic transcript extraction",
      "Key concepts identification",
      "Summary generation",
      "Flashcard creation",
    ],
    color: "text-terracotta",
    bgColor: "bg-terracotta/10",
  },
  {
    icon: FileText,
    title: "Document Intelligence",
    description: "Upload PDFs, resumes, and documents. Our AI parses and understands complex layouts.",
    details: [
      "PDF & document parsing",
      "Resume analysis",
      "Content extraction",
      "Smart formatting",
    ],
    color: "text-azure",
    bgColor: "bg-azure/10",
  },
  {
    icon: Map,
    title: "Dynamic Roadmaps",
    description: "Get personalized learning paths generated by AI based on your goals and current skills.",
    details: [
      "Personalized learning paths",
      "Skill gap analysis",
      "Progress tracking",
      "Adaptive recommendations",
    ],
    color: "text-sage",
    bgColor: "bg-sage/10",
  },
  {
    icon: Code2,
    title: "Code Practice",
    description: "Secure sandbox environment with Monaco Editor. Practice in Python, JavaScript, and more.",
    details: [
      "Real-time code execution",
      "Multiple languages",
      "Test case validation",
      "AI-powered hints",
    ],
    color: "text-lavender",
    bgColor: "bg-lavender/10",
  },
  {
    icon: Briefcase,
    title: "Smart Job Matching",
    description: "AI-powered semantic matching connects you with perfect job opportunities.",
    details: [
      "Skill-based matching",
      "Resume optimization",
      "Application tracking",
      "Interview prep",
    ],
    color: "text-gold",
    bgColor: "bg-gold/10",
  },
  {
    icon: Brain,
    title: "AI Career Assistant",
    description: "Get personalized advice, interview prep, and career guidance powered by advanced AI.",
    details: [
      "24/7 availability",
      "Personalized guidance",
      "Interview simulation",
      "Career planning",
    ],
    color: "text-azure",
    bgColor: "bg-azure/10",
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 24 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: "easeOut" as const },
  },
};

const Features = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="relative pt-32 pb-20 px-4">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-sage/5 rounded-full blur-[120px]" />
          <div className="absolute inset-0 bg-grid-subtle bg-[size:60px_60px] opacity-40" />
        </div>

        <div className="container mx-auto relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          >
            <Badge variant="subtle" className="mb-6">
              <Sparkles className="w-3.5 h-3.5 mr-1.5 text-sage" />
              Platform Features
            </Badge>
            <h1 className="font-serif text-4xl md:text-6xl lg:text-7xl font-medium mb-6 tracking-tight">
              Powerful Features for Your{" "}
              <span className="text-gradient">Success</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Everything you need to accelerate your learning journey and land your dream tech job.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 md:py-24 px-4">
        <div className="container mx-auto">
          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8"
          >
            {features.map((feature) => (
              <motion.div key={feature.title} variants={itemVariants}>
                <Card variant="feature" className="h-full p-8">
                  <div className={`w-14 h-14 rounded-2xl ${feature.bgColor} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300`}>
                    <feature.icon className={`w-7 h-7 ${feature.color}`} />
                  </div>
                  <CardTitle className="text-xl mb-3">{feature.title}</CardTitle>
                  <CardDescription className="text-base mb-6 leading-relaxed">
                    {feature.description}
                  </CardDescription>
                  <ul className="space-y-3">
                    {feature.details.map((detail) => (
                      <li key={detail} className="flex items-center gap-3 text-sm text-muted-foreground">
                        <CheckCircle2 className="w-4 h-4 text-success flex-shrink-0" />
                        {detail}
                      </li>
                    ))}
                  </ul>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 md:py-32 px-4 bg-muted/30">
        <div className="container mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <Badge variant="subtle" className="mb-4">
              <Target className="w-3.5 h-3.5 mr-1.5 text-azure" />
              Getting Started
            </Badge>
            <h2 className="font-serif text-3xl md:text-5xl font-medium mb-6 tracking-tight">
              How It <span className="text-gradient">Works</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Get started in minutes and transform your career path
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12 max-w-4xl mx-auto">
            {[
              { icon: Target, title: "Set Your Goal", description: "Tell us what career path you want to pursue", step: "01" },
              { icon: Map, title: "Get Your Roadmap", description: "AI generates a personalized learning path", step: "02" },
              { icon: Rocket, title: "Start Learning", description: "Practice, learn, and land your dream job", step: "03" },
            ].map((item, index) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1, duration: 0.6 }}
                viewport={{ once: true }}
                className="text-center"
              >
                <div className="relative inline-block mb-6">
                  <div className="w-20 h-20 rounded-2xl bg-primary flex items-center justify-center mx-auto shadow-lg">
                    <item.icon className="w-10 h-10 text-primary-foreground" />
                  </div>
                  <span className="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-card border border-border flex items-center justify-center text-xs font-medium shadow-sm">
                    {item.step}
                  </span>
                </div>
                <h3 className="font-serif text-xl font-medium mb-3">{item.title}</h3>
                <p className="text-muted-foreground">{item.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 md:py-32 px-4">
        <div className="container mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="bg-card rounded-3xl border border-border/50 shadow-elegant p-10 md:p-16 text-center max-w-3xl mx-auto"
          >
            <div className="w-16 h-16 rounded-2xl bg-primary flex items-center justify-center mx-auto mb-8 shadow-lg">
              <Zap className="w-8 h-8 text-primary-foreground" />
            </div>
            <h2 className="font-serif text-3xl md:text-4xl font-medium mb-6 tracking-tight">
              Ready to Get Started?
            </h2>
            <p className="text-lg text-muted-foreground mb-10">
              Join thousands of learners already transforming their careers.
            </p>
            <Button variant="hero" size="xl" asChild>
              <Link to="/auth">
                Start Free Today
                <ArrowRight className="w-5 h-5 ml-2" />
              </Link>
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 border-t border-border/50">
        <div className="container mx-auto text-center text-muted-foreground">
          <p>© 2025 EduForce AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Features;
